import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faUtensils,
  faBoxes,
  faSpinner,
  faSmileWink,
  faCircle,
  faFilePdf,
  faInfoSquare,
  faCheckCircle,
  faEmptySet,
  faSpinnerThird,
  faTimesCircle,
  faMeat,
  faPhone,
  faHome,
  faTruckLoading,
  faSearch,
  faBoxCheck,
  faFileContract,
  faHatChef,
  faWarehouseAlt,
  faBoxOpen,
  faWindTurbine,
  faPlay,
  faCheckSquare,
  faSquare,
  faTachometer,
  faChairOffice,
  faGasPump,
  faPlusSquare,
  faMinusSquare
} from "@fortawesome/pro-light-svg-icons";

library.add(
  faSpinner,
  faBoxes,
  faSmileWink,
  faCircle,
  faFilePdf,
  faEmptySet,
  faCheckCircle,
  faInfoSquare,
  faSpinnerThird,
  faTimesCircle,
  faMeat,
  faPhone,
  faHome,
  faTruckLoading,
  faSearch,
  faBoxCheck,
  faFileContract,
  faHatChef,
  faWarehouseAlt,
  faBoxOpen,
  faWindTurbine,
  faPlay,
  faUtensils,
  faCheckSquare,
  faSquare,
  faTachometer,
  faChairOffice,
  faGasPump,
  faPlusSquare,
  faMinusSquare
);

export default library;
